# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20404e593c0cf874d3e6000e499ab657282f29f7ecffbf34daa8b21df4747060fd4bf759c27ba4eb647ca4f83e90dc2f9b7cd7fed906b3cb15a25242328fd122

test:
  secret_key_base: 63089df03156c4d75031571d6003cacf304ac4440d5cc361c49c70b556f2069e9de22fc1a2ded29d76d1ba8dbf1f9656cb74f04ac1f2b22c6606272fff969aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
